# -*- coding: utf-8 -*-
NUMBER = '01'
CHAR_SMALL = 'ab'
CHAR_BIG = 'AB'

MAX_CAPTCHA = 4  # 测试1位的训练准确率
VALIDATE_STRING = NUMBER  # + CHAR_SMALL #+ CHAR_BIG
CHAR_SET_LEN = len(VALIDATE_STRING)

#图片的长宽高
IMAGE_HEIGHT = 60
IMAGE_WIDTH = 160
FONT_SIZE = 35

MAX_ACCURACY = 0.95
